name: Update README Version

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get the latest tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update README and Push
        run: |
          sed -i "s/Launcher v[0-9.]*/Launcher ${{ steps.get_tag.outputs.TAG }}/g" README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes in README.md
          if [ -n "$(git status --porcelain README.md)" ]; then
            git add README.md
            git commit -m "update README version to v1.4.0"
            git push origin main
          else
            echo "No changes detected in README.md, skipping commit."
          fi
